export const SET_US_UNITS_FORM_DATA = 'SET_US_UNITS_FORM_DATA'
export const SET_METRIC_UNITS_FORM_DATA = 'SET_METRIC_UNITS_FORM_DATA'

export const CALCULATE_US_UNITS_FORM = 'CALCULATE_US_UNITS_FORM'
export const CALCULATE_US_UNITS_FORM_SUCCESS = 'CALCULATE_US_UNITS_FORM_SUCCESS'
export const CALCULATE_US_UNITS_FORM_FAILED = 'CALCULATE_US_UNITS_FORM_FAILED'

export const CALCULATE_METRIC_UNITS_FORM = 'CALCULATE_METRIC_UNITS_FORM'
export const CALCULATE_METRIC_UNITS_FORM_SUCCESS = 'CALCULATE_METRIC_UNITS_FORM_SUCCESS'
export const CALCULATE_METRIC_UNITS_FORM_FAILED = 'CALCULATE_METRIC_UNITS_FORM_SUCCESS'

export const SET_CURRENT_TAB = 'SET_CURRENT_TAB'